# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PractitionerWaitlistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=180)),
                ('headline', models.CharField(max_length=220)),
                ('modalities', models.CharField(help_text='Comma-separated offerings', max_length=255)),
                ('practice_type', models.CharField(choices=[('wellness', 'Wellness'), ('spiritual', 'Spiritual'), ('beauty', 'Beauty'), ('coaching', 'Coaching'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('is_virtual', models.BooleanField(default=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('website_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
