# Generated by Django 6.0.3 on 2026-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_practitionerwaitlistprofile_offers_in_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitionerwaitlistprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
