# Generated by Django 6.0.3 on 2026-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_alter_practitionerwaitlistprofile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerwaitlistprofile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('invited', 'Invited'), ('onboarded', 'Onboarded')], db_index=True, default='new', max_length=20),
        ),
    ]
