# Generated by Django 6.0.3 on 2026-03-18 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0004_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerwaitlistprofile',
            name='status_changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
