# Generated by Django 6.0.3 on 2026-03-18 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0005_status_changed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('invited', 'Invited'), ('onboarded', 'Onboarded')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('invited', 'Invited'), ('onboarded', 'Onboarded')], max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for status change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_transitions_changed', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='waitlist.practitionerwaitlistprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['profile', '-changed_at'], name='waitlist_st_profile_8485a9_idx')],
            },
        ),
    ]
