# Generated by Django 6.0.3 on 2026-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0006_add_status_transition_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerwaitlistprofile',
            name='is_founding_member',
            field=models.BooleanField(default=False, help_text='Opted in for the founding practitioner rate at sign-up.'),
        ),
    ]
