# Generated by Django 6.0.3 on 2026-04-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0010_invitecode_waitlistlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_invite_codes', to='waitlist.waitlistlead'),
        ),
        migrations.AddField(
            model_name='waitlistlead',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='uses_remaining',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='waitlistlead',
            name='invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waitlist.invitecode'),
        ),
    ]
