# Generated by Django 6.0.3 on 2026-04-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0011_invitecode_owner_waitlistlead_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='Admin user responsible for this invite code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_owned_invite_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
