# Generated by Django 6.0.3 on 2026-04-01 07:13

import re
from django.db import migrations


def _normalize(raw):
    cleaned = re.sub(r"[^A-Za-z0-9]", "", raw or "").upper()
    if len(cleaned) == 6:
        return f"{cleaned[:3]}-{cleaned[3:]}"
    return raw.upper() if raw else raw


def normalize_existing_codes(apps, schema_editor):
    InviteCode = apps.get_model("waitlist", "InviteCode")
    for invite in InviteCode.objects.all():
        normalized = _normalize(invite.code)
        if normalized != invite.code:
            invite.code = normalized
            invite.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0012_invitecode_admin_owner'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_codes, migrations.RunPython.noop),
    ]
