# Generated by Django 6.0.3 on 2026-04-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0013_normalize_invitecode_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistlead',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
