# Generated by Django 6.0.3 on 2026-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0014_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistlead',
            name='confirmation_email_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
