# Generated by Django 6.0.3 on 2026-03-17 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('headline', models.CharField(max_length=220)),
                ('bio', models.TextField()),
                ('modalities', models.CharField(help_text='Comma-separated offerings', max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('is_virtual', models.BooleanField(default=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
    ]
