# Generated by Django 6.0.3 on 2026-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'ordering': ['user__display_name', 'business_name']},
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
