# Generated by Django 6.0.3 on 2026-03-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professionalprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Staff-verified badge shown publicly on the profile page.'),
        ),
    ]
