# Generated by Django 6.0.3 on 2026-03-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='long_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='professionals/profile_photos/'),
        ),
        migrations.CreateModel(
            name='ProfessionalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('certification', 'Certification'), ('education', 'Education'), ('license', 'License'), ('other', 'Other')], default='certification', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('license_number', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfileGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='professionals/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
