# Generated by Django 6.0.3 on 2026-03-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalprofile_long_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='subscription_fails_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='subscription_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('prelaunch', 'Prelaunch Access'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('grandfathered', 'Grandfathered')], db_index=True, default='not_started', max_length=20),
        ),
    ]
