# Generated by Django 6.0.3 on 2026-03-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingpaymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentintent',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpaymentintent',
            name='requires_manual_refund',
            field=models.BooleanField(default=False),
        ),
    ]
