# Generated by Django 6.0.3 on 2026-03-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingpaymentintent_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentintent',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Stripe refund ID (re_...) once issued.', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingpaymentintent',
            name='refund_resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the manual refund was marked resolved.', null=True),
        ),
    ]
